'use client'

import { useEffect, useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowRight, Code2, ExternalLink, Gamepad2, Github, GraduationCap, Layers3, MapPin, Megaphone, PenTool, Rocket, Sparkles, Terminal, Trophy, Clapperboard } from 'lucide-react'
import s from '@/components/arcade/Arcade.module.css'
import ImageForge from '@/components/arcade/ImageForge'
import UmayOSDemo from '@/components/arcade/UmayOSDemo'
import EasterEggLayer from '@/components/arcade/EasterEggLayer'
import Reveal from '@/components/fx/Reveal'
import TiltCard from '@/components/fx/TiltCard'
import Magnetic from '@/components/fx/Magnetic'

type Shot = { src: string; source: string; title: string }

function StoreWall(){
  const [shots,setShots]=useState<Shot[]>([])
  const [live,setLive]=useState(false)
  useEffect(()=>{fetch('/api/store').then(r=>r.json()).then(d=>{setShots(d.images||[]);setLive(Boolean(d.live))}).catch(()=>setShots([]))},[])
  const images=useMemo(()=>[...shots,...shots,...shots].slice(0,21),[shots])
  return <div className={s.storeWall}><div className={s.storeTop}><div><p>LIVE STORE FEED</p><h3>Dirty Birdy! screenshot carousel</h3></div><span>{live?'GOOGLE PLAY / APP STORE':'FALLBACK MODE'}</span></div><motion.div className={s.track} animate={{x:['0%','-45%']}} transition={{duration:34,repeat:Infinity,ease:'linear'}}>{images.map((img,i)=><motion.a href="https://play.google.com/store/apps/details?id=com.moonlight.dirtybirdy&hl=tr&pli=1" target="_blank" rel="noreferrer" whileHover={{y:-18,rotate:i%2?3:-3,scale:1.045}} className={s.phone} key={`${img.src}-${i}`}><img src={img.src} alt={img.title}/><b>{img.source}</b></motion.a>)}</motion.div></div>
}

function Section({id,label,title,children}:{id?:string;label:string;title:string;children:React.ReactNode}){return <section id={id} className={s.section}><Reveal><div className={s.label}>{label}</div><h2 className={s.heading}>{title}</h2></Reveal><Reveal delay={0.08}>{children}</Reveal></section>}

export default function Home(){
  return <main className={s.site}><EasterEggLayer/>
    <section className={s.hero}><div><div className={s.pill}><Rocket/> Portfolio build: playful, cinematic, store-connected</div><h1 className={s.title}>Emirhan<br/>Doygun</h1><p className={s.lead}>Computer Engineering student, creative content producer, motion designer and game-focused builder. This is a playable portfolio with live Dirty Birdy! visuals, a working ImageForge tool, UmayOS mini demo, Metraj Production motion work, CV dashboard and arcade energy.</p><div className={s.actions}><Magnetic className="inline-block"><a href="#dirty">Open Dirty Birdy! Lab <ArrowRight/></a></Magnetic><Magnetic className="inline-block"><a href="#umayos">Boot UmayOS <Terminal/></a></Magnetic><Magnetic className="inline-block"><a href="https://github.com/Remirdy" target="_blank" rel="noreferrer"><Github/>GitHub</a></Magnetic></div><div className={s.meta}><span><MapPin/>Istanbul</span><span><Terminal/>Interactive portfolio runtime</span></div></div><div className={s.visual}><div className={s.orbitA}/><div className={s.orbitB}/><div className={s.rayA}/><div className={s.rayB}/><div className={s.console}><div className={s.consoleHead}><Terminal/>CREATIVE RUNTIME</div>{['Game Feel','PSD Animation','AI Motion','UmayOS'].map((x,i)=><div className={s.row} key={x}><div className={s.rowTop}><span>{x}</span><em>{96-i*8}%</em></div><div className={s.bar}><i style={{width:`${96-i*8}%`}}/></div></div>)}</div><div className={`${s.cube} ${s.cubeA}`}>IF</div><div className={`${s.cube} ${s.cubeB}`}>AI</div><div className={s.chaos}><div className={s.chaosTop}><span>Production Meter</span><b>MAX</b></div><div className={s.chaosMeter}/><div className={s.rowTop}><span>GAME</span><span>PSD</span><span>AI</span></div></div><div className={s.emoji}><span>🐦</span><span>💥</span><span>🎬</span><span>🚀</span></div></div></section>
    <Section id="dirty" label="01 / Live case study" title="Dirty Birdy! Chaos Lab"><div className={s.twoCol}><div><p className={s.lead}>A game case-study area powered by the store links you provided. The site pulls public store screenshots and turns them into a moving arcade wall.</p><div className={s.tags}>{['Software Developer','Storyboard Creator','Character Universe','UI / HUD Direction'].map(x=><span key={x}>{x}</span>)}</div><div className={s.cardGrid}>{[['Gameplay','Mechanics, system thinking and UI/UX implementation.',Gamepad2],['Character Bible','Characters, emotional range, flight references and animated rules.',PenTool],['Trailer Language','Beat-by-beat scenes, motion timing and visual rhythm.',Trophy]].map(([t,p,Icon])=><TiltCard className={`${s.card} group relative`} key={t as string}><Icon/><h3>{t as string}</h3><p>{p as string}</p></TiltCard>)}</div><a className={s.storeLink} href="https://play.google.com/store/apps/details?id=com.moonlight.dirtybirdy&hl=tr&pli=1" target="_blank" rel="noreferrer">Open Google Play <ExternalLink/></a></div><StoreWall/></div></Section>
    <Section id="imageforge" label="02 / Working browser tool" title="ImageForge Creator Tool"><p className={s.lead}>ImageForge now works inside the portfolio: upload an image, choose a social preset, switch cover/contain mode, and download a resized PNG directly from the browser.</p><ImageForge/></Section>
    <Section id="umayos" label="03 / Working mini demo" title="UmayOS Mini TV Demo"><div className={s.twoCol}><div><p className={s.lead}>UmayOS is no longer just a concept card. It is a small retro television-style mini desktop: the system boots, terminal lines run, the dock appears, and the screen types REMIRDY as the signature output.</p><div className={s.tags}>{['Boot Demo','REMIRDY Terminal','Retro TV UI','Widget Dock','Mini Desktop','Reboot Button'].map(x=><span key={x}>{x}</span>)}</div><div className={s.cardGrid}>{[['Command Center','A central dashboard for projects, shortcuts and creator tools.',Terminal],['Widget Layer','Glassmorphic cards for notes, media, tasks and live project states.',Layers3],['Interaction Feel','Boot, sleep, reboot, dock and terminal feedback inside the portfolio.',Sparkles]].map(([t,p,Icon])=><TiltCard className={`${s.card} group relative`} key={t as string}><Icon/><h3>{t as string}</h3><p>{p as string}</p></TiltCard>)}</div></div><UmayOSDemo/></div></Section>
    <Section id="madlab" label="04 / Hidden interaction layer" title="Secret Portfolio Modes"><div className={s.cardGrid}>{[['Bird Storm Protocol','A concealed input route opens a cinematic overlay with falling symbols and a runtime monitor.',Sparkles],['UmayOS Backdoor','A second hidden route connects the operating-system section with a secret compositor layer.',Terminal],['Signature Mode','A third route activates the strongest identity layer with REMIRDY-coded visual rain.',Layers3]].map(([t,p,Icon])=><TiltCard className={`${s.card} group relative`} key={t as string}><Icon/><h3>{t as string}</h3><p>{p as string}</p></TiltCard>)}</div></Section>
    <Section id="metraj" label="05 / Agency motion work" title="Metraj Production Motion Studio"><div className={s.twoCol}><div><p className={s.lead}>At Metraj Production, I worked inside an agency production flow focused on animation and visual enhancement. I did not create the PSD files from scratch; I animated ready-made layered PSD designs, brought static compositions to life, and supported image-to-motion production with professional AI tools. My work focused on transforming prepared visuals into polished moving assets through timing, depth, parallax, camera movement, transitions and refined motion rhythm.</p><div className={s.tags}>{['Ready PSD Animation','After Effects Workflow','AI Image-to-Motion','Layer Animation','Parallax Depth','Agency Production'].map(x=><span key={x}>{x}</span>)}</div></div><div className={s.cardGrid}>{[['Ready PSD Animation','Animating existing Photoshop layouts by separating visual beats, timing layer reveals and building clean motion hierarchy.',Clapperboard],['AI Motion Enhancement','Using professional AI motion tools to animate visual assets, extend static imagery into movement and support faster creative iteration.',Sparkles],['Production Mindset','Working with agency speed: revision-friendly motion, readable compositions, clean delivery and polished visual output.',Megaphone]].map(([t,p,Icon])=><TiltCard className={`${s.card} group relative`} key={t as string}><Icon/><h3>{t as string}</h3><p>{p as string}</p></TiltCard>)}</div></div></Section>
    <Section id="cv" label="06 / CV systems" title="Experience, Education & Skills"><div className={s.cvGrid}>{[['Computer Engineering','Istanbul Commerce University, B.Sc. Computer Engineering, 2024 - Present',GraduationCap],['MoonLight','Digital marketing, prompt engineering, campaign visuals, Reels/TikTok content, Pinterest concepts and CTA lines.',Megaphone],['Metraj Production','Agency motion work: animating ready-made PSD designs, using professional AI tools to bring visuals into motion, and turning static compositions into dynamic video assets.',Clapperboard],['Dirty Birdy! Development','Software contribution, game mechanics, system thinking, UI/UX implementation, character universe and trailer storyboard work.',Gamepad2]].map(([t,p,Icon])=><TiltCard className={`${s.cvCard} group relative`} key={t as string}><Icon/><h3>{t as string}</h3><p>{p as string}</p></TiltCard>)}</div></Section>
    <Section id="skills" label="07 / Skill inventory" title="Technical + Creative Inventory"><div className={s.inventoryGrid}>{[['Technical',['Python','C','C++','C#','Kotlin','Unity','GitHub','React'],Code2],['Creative',['Character Design','Storyboarding','Cinematic Scriptwriting','Visual Storytelling','Ready PSD Animation','AI Image-to-Motion','Motion Graphics'],Sparkles],['Languages',['Turkish Native','English C1','German B1','Spanish A1'],GraduationCap],['Activities',['eTwinning European Quality Label','Piano performance','Debate club','Leadership'],Trophy]].map(([t,list,Icon])=><div className={s.inventory} key={t as string}><Icon/><h3>{t as string}</h3>{(list as string[]).map(x=><span key={x}>{x}</span>)}</div>)}</div></Section>
  </main>
}
