'use client'

import { useEffect, useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowRight, Code2, ExternalLink, Gamepad2, Github, GraduationCap, Layers3, MapPin, Megaphone, PenTool, Rocket, Sparkles, Terminal, Trophy, Clapperboard } from 'lucide-react'
import s from '@/components/arcade/Arcade.module.css'

type Shot = { src: string; source: string; title: string }

function StoreWall(){
  const [shots,setShots]=useState<Shot[]>([])
  const [live,setLive]=useState(false)
  useEffect(()=>{fetch('/api/store').then(r=>r.json()).then(d=>{setShots(d.images||[]);setLive(Boolean(d.live))}).catch(()=>setShots([]))},[])
  const images=useMemo(()=>[...shots,...shots,...shots].slice(0,21),[shots])
  return <div className={s.storeWall}><div className={s.storeTop}><div><p>LIVE STORE FEED</p><h3>Dirty Birdy! screenshot carousel</h3></div><span>{live?'GOOGLE PLAY / APP STORE':'FALLBACK MODE'}</span></div><motion.div className={s.track} animate={{x:['0%','-45%']}} transition={{duration:34,repeat:Infinity,ease:'linear'}}>{images.map((img,i)=><motion.a href="https://play.google.com/store/apps/details?id=com.moonlight.dirtybirdy&hl=tr&pli=1" target="_blank" rel="noreferrer" whileHover={{y:-18,rotate:i%2?3:-3,scale:1.045}} className={s.phone} key={`${img.src}-${i}`}><img src={img.src} alt={img.title}/><b>{img.source}</b></motion.a>)}</motion.div></div>
}

function Section({id,label,title,children}:{id?:string;label:string;title:string;children:React.ReactNode}){return <section id={id} className={s.section}><div className={s.label}>{label}</div><h2 className={s.heading}>{title}</h2>{children}</section>}

export default function Home(){
  return <main className={s.site}>
    <section className={s.hero}><div><div className={s.pill}><Rocket/> Portfolio build: playful, cinematic, store-connected</div><h1 className={s.title}>Emirhan<br/>Doygun</h1><p className={s.lead}>Computer Engineering student, creative content producer, motion designer and game-focused builder. This is a playable portfolio with live Dirty Birdy! visuals, ImageForge, Metraj Production motion work, CV dashboard and arcade energy.</p><div className={s.actions}><a href="#dirty">Open Dirty Birdy! Lab <ArrowRight/></a><a href="https://github.com/Remirdy" target="_blank" rel="noreferrer"><Github/>GitHub</a></div><div className={s.meta}><span><MapPin/>Istanbul</span><span><Terminal/>Game Dev + Motion + Creative Tech</span></div></div><div className={s.visual}><div className={s.orbitA}/><div className={s.orbitB}/><div className={s.rayA}/><div className={s.rayB}/><div className={s.console}><div className={s.consoleHead}><Terminal/>CREATIVE RUNTIME</div>{['Game Feel','PSD Motion','Storyboards','Campaign Ideas'].map((x,i)=><div className={s.row} key={x}><div className={s.rowTop}><span>{x}</span><em>{96-i*8}%</em></div><div className={s.bar}><i style={{width:`${96-i*8}%`}}/></div></div>)}</div><div className={`${s.cube} ${s.cubeA}`}>U</div><div className={`${s.cube} ${s.cubeB}`}>AE</div><div className={s.chaos}><div className={s.chaosTop}><span>Production Meter</span><b>MAX</b></div><div className={s.chaosMeter}/><div className={s.rowTop}><span>GAME</span><span>PSD</span><span>CV</span></div></div><div className={s.emoji}><span>🐦</span><span>💥</span><span>🎬</span><span>🚀</span></div></div></section>
    <Section id="dirty" label="01 / Live case study" title="Dirty Birdy! Chaos Lab"><div className={s.twoCol}><div><p className={s.lead}>A game case-study area powered by the store links you provided. The site pulls public store screenshots and turns them into a moving arcade wall.</p><div className={s.tags}>{['Software Developer','Storyboard Creator','Character Universe','UI / HUD Direction'].map(x=><span key={x}>{x}</span>)}</div><div className={s.cardGrid}>{[['Gameplay','Mechanics, system thinking and UI/UX implementation.',Gamepad2],['Character Bible','Characters, emotional range, flight references and animated rules.',PenTool],['Trailer Language','Beat-by-beat scenes, motion timing and visual rhythm.',Trophy]].map(([t,p,Icon])=><article className={s.card} key={t as string}><Icon/><h3>{t as string}</h3><p>{p as string}</p></article>)}</div><a className={s.storeLink} href="https://play.google.com/store/apps/details?id=com.moonlight.dirtybirdy&hl=tr&pli=1" target="_blank" rel="noreferrer">Open Google Play <ExternalLink/></a></div><StoreWall/></div></Section>
    <Section id="imageforge" label="02 / Product concept" title="ImageForge Creator Tool"><div className={s.forge}><div><p className={s.lead}>ImageForge is a creator tool concept for image resizing, crop control, preset exports and batch production.</p><div className={s.tags}>{['Smart crop frames','Batch export queue','Social preset cards','Before / after preview','Drag and drop','Creator-first UI'].map(x=><span key={x}>{x}</span>)}</div></div><div className={s.forgeUI}><div className={s.canvas}><Layers3/><span>DROP IMAGE</span></div><div className={s.panelMini}><b>Export queue</b><i style={{width:'92%'}}/><i style={{width:'76%'}}/><i style={{width:'58%'}}/><button>EXPORT ALL</button></div></div></div></Section>
    <Section id="metraj" label="03 / Agency motion work" title="Metraj Production Motion Studio"><div className={s.twoCol}><div><p className={s.lead}>At Metraj Production, I worked in an agency production flow where static Photoshop designs became animated visuals. I prepared layered PSD compositions for motion, animated separate visual parts, built clean reveal timing, depth, parallax, camera movement and premium transition rhythm.</p><div className={s.tags}>{['PSD to Motion','After Effects Workflow','Layer Animation','Parallax Depth','Kinetic Reveals','Agency Production'].map(x=><span key={x}>{x}</span>)}</div></div><div className={s.cardGrid}>{[['PSD Layer Choreography','Turning Photoshop layers into staged motion scenes with masks, timing and visual hierarchy.',Clapperboard],['Motion Polish','Adding camera pushes, glow, shadow, depth, easing and transition rhythm.',Sparkles],['Production Mindset','Clean handoffs, readable compositions, revision-friendly motion and polished deliverables.',Megaphone]].map(([t,p,Icon])=><article className={s.card} key={t as string}><Icon/><h3>{t as string}</h3><p>{p as string}</p></article>)}</div></div></Section>
    <Section id="cv" label="04 / CV systems" title="Experience, Education & Skills"><div className={s.cvGrid}>{[['Computer Engineering','Istanbul Commerce University, B.Sc. Computer Engineering, 2024 - Present',GraduationCap],['MoonLight','Digital marketing, prompt engineering, campaign visuals, Reels/TikTok content, Pinterest concepts and CTA lines.',Megaphone],['Metraj Production','Agency motion work: animating PSD designs, creating layered reveal systems and turning static compositions into dynamic video assets.',Clapperboard],['Dirty Birdy! Development','Software contribution, game mechanics, system thinking, UI/UX implementation, character universe and trailer storyboard work.',Gamepad2]].map(([t,p,Icon])=><article className={s.cvCard} key={t as string}><Icon/><h3>{t as string}</h3><p>{p as string}</p></article>)}</div></Section>
    <Section id="skills" label="05 / Skill inventory" title="Technical + Creative Inventory"><div className={s.inventoryGrid}>{[['Technical',['Python','C','C++','C#','Kotlin','Unity','GitHub','React'],Code2],['Creative',['Character Design','Storyboarding','Cinematic Scriptwriting','Visual Storytelling','PSD Animation','Motion Graphics'],Sparkles],['Languages',['Turkish Native','English C1','German B1','Spanish A1'],GraduationCap],['Activities',['eTwinning European Quality Label','Piano performance','Debate club','Leadership'],Trophy]].map(([t,list,Icon])=><div className={s.inventory} key={t as string}><Icon/><h3>{t as string}</h3>{(list as string[]).map(x=><span key={x}>{x}</span>)}</div>)}</div></Section>
  </main>
}
