'use client'

import { useEffect, useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowRight, Code2, ExternalLink, Gamepad2, Github, GraduationCap, Layers3, MapPin, Megaphone, PenTool, Rocket, Sparkles, Terminal, Trophy, Clapperboard } from 'lucide-react'
import s from '@/components/arcade/Arcade.module.css'
import ImageForge from '@/components/arcade/ImageForge'
import ImageForgeDashboard from '@/components/arcade/ImageForgeDashboard'
import UmayOSDemo from '@/components/arcade/UmayOSDemo'
import PhoneSimulator from '@/components/arcade/PhoneSimulator'
import EasterEggLayer from '@/components/arcade/EasterEggLayer'
import Reveal from '@/components/fx/Reveal'
import TiltCard from '@/components/fx/TiltCard'
import Magnetic from '@/components/fx/Magnetic'


type Shot = { src: string; source: string; title: string }

function StoreWall(){
  const [shots,setShots]=useState<Shot[]>([])
  const [live,setLive]=useState(false)
  useEffect(()=>{fetch('/api/store').then(r=>r.json()).then(d=>{setShots(d.images||[]);setLive(Boolean(d.live))}).catch(()=>setShots([]))},[])
  const images=useMemo(()=>[...shots,...shots,...shots].slice(0,21),[shots])
  return <div className={s.storeWall}><div className={s.storeTop}><div><p>LIVE STORE FEED</p><h3>Dirty Birdy! screenshot carousel</h3></div><span>{live?'GOOGLE PLAY / APP STORE':'FALLBACK MODE'}</span></div><motion.div className={s.track} animate={{x:['0%','-45%']}} transition={{duration:34,repeat:Infinity,ease:'linear'}}>{images.map((img,i)=><motion.a href="https://play.google.com/store/apps/details?id=com.moonlight.dirtybirdy&hl=tr&pli=1" target="_blank" rel="noreferrer" whileHover={{y:-18,rotate:i%2?3:-3,scale:1.045}} className={s.phone} key={`${img.src}-${i}`}><img src={img.src} alt={img.title}/><b>{img.source}</b></motion.a>)}</motion.div></div>
}

function Section({id,label,title,children}:{id?:string;label:string;title:string;children:React.ReactNode}){return <section id={id} className={s.section}><Reveal><div className={s.label}>{label}</div><h2 className={s.heading}>{title}</h2></Reveal><Reveal delay={0.08}>{children}</Reveal></section>}

export default function Home(){
  return <main className={s.site}><EasterEggLayer/>
    <section className={s.hero}><div><div className={s.pill}><Rocket/> Portfolio build: playful, cinematic, store-connected</div><h1 className={s.title}>Emirhan<br/>Doygun</h1><p className={s.lead}>Computer Engineering student, creative content producer, motion designer and game-focused builder. This is a playable portfolio with live Dirty Birdy! visuals, a working ImageForge tool, After Effects MCP automation, UmayOS mini demo, Metraj Production motion work, CV dashboard and arcade energy.</p><div className={s.actions}><Magnetic className="inline-block"><a href="#dirty">Open Dirty Birdy! Lab <ArrowRight/></a></Magnetic><Magnetic className="inline-block"><a href="#umayos">Boot UmayOS <Terminal/></a></Magnetic><Magnetic className="inline-block"><a href="https://github.com/Remirdy" target="_blank" rel="noreferrer"><Github/>GitHub</a></Magnetic></div><div className={s.meta}><span><MapPin/>Istanbul</span><span><Terminal/>Interactive portfolio runtime</span></div></div><div className={s.visual}><div className={s.orbitA}/><div className={s.orbitB}/><div className={s.rayA}/><div className={s.rayB}/><div className={s.console}><div className={s.consoleHead}><Terminal/>CREATIVE RUNTIME</div>{['Game Feel','AE MCP','AI Motion','UmayOS'].map((x,i)=><div className={s.row} key={x}><div className={s.rowTop}><span>{x}</span><em>{96-i*8}%</em></div><div className={s.bar}><i style={{width:`${96-i*8}%`}}/></div></div>)}</div><div className={`${s.cube} ${s.cubeA}`}>IF</div><div className={`${s.cube} ${s.cubeB}`}>AI</div><div className={s.chaos}><div className={s.chaosTop}><span>Production Meter</span><b>MAX</b></div><div className={s.chaosMeter}/><div className={s.rowTop}><span>GAME</span><span>PSD</span><span>AI</span></div></div><div className={s.emoji}><span>🐦</span><span>💥</span><span>🎬</span><span>🚀</span></div></div></section>
    <Section id="dirty" label="01 / Live case study" title="Dirty Birdy! Chaos Lab"><div className={s.twoCol}><div><p className={s.lead}>A game case-study area powered by the store links you provided. The site pulls public store screenshots and turns them into a moving arcade wall.</p><div className={s.tags}>{['Software Developer','Storyboard Creator','Character Universe','UI / HUD Direction'].map(x=><span key={x}>{x}</span>)}</div><div className={s.cardGrid}>{([['Gameplay','Mechanics, system thinking and UI/UX implementation.',Gamepad2],['Character Bible','Characters, emotional range, flight references and animated rules.',PenTool],['Trailer Language','Beat-by-beat scenes, motion timing and visual rhythm.',Trophy]] as [string,string,React.ComponentType<Record<string, unknown>>][]).map(([t,p,Icon])=><TiltCard className={`${s.card} group relative`} key={t as string}><Icon/><h3>{t as string}</h3><p>{p as string}</p></TiltCard>)}</div><a className={s.storeLink} href="https://play.google.com/store/apps/details?id=com.moonlight.dirtybirdy&hl=tr&pli=1" target="_blank" rel="noreferrer">Open Google Play <ExternalLink/></a></div><StoreWall/></div></Section>
    <Section id="imageforge" label="02 / SaaS product design" title="ImageForge — Image Resizer & Batch Export Tool"><p className={s.lead}>A powerful yet simple SaaS tool that helps creators, marketers and teams resize images and export them in bulk — faster, smarter, together. Smart resizing, batch export, export presets for social / e-commerce / print, and cloud-powered processing.</p><div className={s.tags}>{['Smart Resizing','Batch Export','Export Presets','Cloud Powered','Team Workflows'].map(x=><span key={x}>{x}</span>)}</div><ImageForgeDashboard/><p className={s.lead} style={{marginTop:'2rem'}}>And it is not just a mockup — try the working browser tool below: upload an image, choose a social preset, switch cover/contain mode, and download a resized PNG instantly.</p><ImageForge/></Section>
    <Section id="aftereffects-mcp" label="03 / Creative automation tool" title="After Effects MCP — MotionPilot"><div className={s.twoCol}><div><p className={s.lead}>A local MCP server that connects AI agents to Adobe After Effects. It analyzes PSD files, creates structured motion plans, imports compositions into After Effects, applies keyframes, builds VFX systems, and can render preview videos while preserving source assets and text content.</p><div className={s.tags}>{['MCP Server','Adobe After Effects','PSD Analysis','ExtendScript JSX','Motion Planning','VFX Automation','AEP Output','Render Preview'].map(x=><span key={x}>{x}</span>)}</div><div className={s.actions} style={{marginTop:'1.4rem'}}><Magnetic className="inline-block"><a href="https://github.com/Remirdy/AfterEffectsMCP" target="_blank" rel="noreferrer"><Github/>View repository</a></Magnetic><Magnetic className="inline-block"><a href="#metraj">See motion workflow <ArrowRight/></a></Magnetic></div></div><div className={s.cardGrid}>{([['AI-to-AE Pipeline','Turns PSD structure and a creative direction into an After Effects project with motion plans, keyframes, easing and render-ready outputs.',Terminal],['Production Safety','Keeps PSD files read-only, saves new AEP files, protects text content, and requires explicit overwrite approval for generated files.',Code2],['VFX Engine','Includes game, cinema and social VFX presets with stock-AE fallbacks plus Unity / Unreal-ready package workflows.',Sparkles]] as [string,string,React.ComponentType<Record<string, unknown>>][]).map(([t,p,Icon])=><TiltCard className={`${s.card} group relative`} key={t as string}><Icon/><h3>{t as string}</h3><p>{p as string}</p></TiltCard>)}</div></div></Section>
    <Section id="umayos" label="04 / Working mini demo" title="UmayOS Mini TV Demo"><div className={s.twoCol}><div><p className={s.lead}>UmayOS is no longer just a concept card. It is a small retro television-style mini desktop: the system boots, terminal lines run, the dock appears, and the screen types REMIRDY as the signature output.</p><div className={s.tags}>{['Boot Demo','REMIRDY Terminal','Retro TV UI','Widget Dock','Mini Desktop','Reboot Button'].map(x=><span key={x}>{x}</span>)}</div><div className={s.cardGrid}>{([['Command Center','A central dashboard for projects, shortcuts and creator tools.',Terminal],['Widget Layer','Glassmorphic cards for notes, media, tasks and live project states.',Layers3],['Interaction Feel','Boot, sleep, reboot, dock and terminal feedback inside the portfolio.',Sparkles]] as [string,string,React.ComponentType<Record<string, unknown>>][]).map(([t,p,Icon])=><TiltCard className={`${s.card} group relative`} key={t as string}><Icon/><h3>{t as string}</h3><p>{p as string}</p></TiltCard>)}</div></div><UmayOSDemo/></div></Section>
    <Section id="ecoquest" label="05 / Native Android product" title="EcoQuest — Sustainability Habit Tracker"><div className={s.twoCol}><div><p className={s.lead}>A gamified sustainability app that turns eco-friendly habits into a game: complete daily missions, earn XP and Eco Points, keep streaks, unlock badges, and grow a living virtual garden. Shipped as a real native Android app and as a fully playable browser experience inside this portfolio.</p><div className={s.tags}>{['Kotlin','Jetpack Compose','Material 3','MVVM','DataStore','EN / TR'].map(x=><span key={x}>{x}</span>)}</div><div className={s.actions} style={{marginTop:'1.4rem'}}><Magnetic className="inline-block"><a href="/ecoquest">Open live demo <ArrowRight/></a></Magnetic><Magnetic className="inline-block"><a href="https://github.com/Remirdy/EcoQuest" target="_blank" rel="noreferrer"><Github/>Android source</a></Magnetic></div></div><PhoneSimulator /></div></Section>
    <Section id="madlab" label="06 / Hidden interaction layer" title="Secret Portfolio Modes"><div className={s.cardGrid}>{([['Bird Storm Protocol','A concealed input route opens a cinematic overlay with falling symbols and a runtime monitor.',Sparkles],['UmayOS Backdoor','A second hidden route connects the operating-system section with a secret compositor layer.',Terminal],['Signature Mode','A third route activates the strongest identity layer with REMIRDY-coded visual rain.',Layers3]] as [string,string,React.ComponentType<Record<string, unknown>>][]).map(([t,p,Icon])=><TiltCard className={`${s.card} group relative`} key={t as string}><Icon/><h3>{t as string}</h3><p>{p as string}</p></TiltCard>)}</div></Section>
    <Section id="metraj" label="07 / Agency motion work" title="Metraj Production Motion Studio"><div className={s.twoCol}><div><p className={s.lead}>At Metraj Production, I worked inside an agency production flow focused on animation and visual enhancement. I did not create the PSD files from scratch; I animated ready-made layered PSD designs, brought static compositions to life, and supported image-to-motion production with professional AI tools. My work focused on transforming prepared visuals into polished moving assets through timing, depth, parallax, camera movement, transitions and refined motion rhythm.</p><div className={s.tags}>{['Ready PSD Animation','After Effects Workflow','AI Image-to-Motion','Layer Animation','Parallax Depth','Agency Production'].map(x=><span key={x}>{x}</span>)}</div><div className={s.actions} style={{marginTop:'1.4rem'}}><Magnetic className="inline-block"><a href="/motion">Örnek çalışmaları gör <ArrowRight/></a></Magnetic></div></div><div className={s.cardGrid}>{([['Ready PSD Animation','Animating existing Photoshop layouts by separating visual beats, timing layer reveals and building clean motion hierarchy.',Clapperboard],['AI Motion Enhancement','Using professional AI motion tools to animate visual assets, extend static imagery into movement and support faster creative iteration.',Sparkles],['Production Mindset','Working with agency speed: revision-friendly motion, readable compositions, clean delivery and polished visual output.',Megaphone]] as [string,string,React.ComponentType<Record<string, unknown>>][]).map(([t,p,Icon])=><TiltCard className={`${s.card} group relative`} key={t as string}><Icon/><h3>{t as string}</h3><p>{p as string}</p></TiltCard>)}</div></div></Section>
    <Section id="cv" label="08 / CV systems" title="Experience, Education & Skills"><div className={s.cvGrid}>{([['Computer Engineering','Istanbul Commerce University, B.Sc. Computer Engineering, 2024 - Present',GraduationCap],['MoonLight','Digital marketing, prompt engineering, campaign visuals, Reels/TikTok content, Pinterest concepts and CTA lines.',Megaphone],['Metraj Production','Agency motion work: animating ready-made PSD designs, using professional AI tools to bring visuals into motion, and turning static compositions into dynamic video assets.',Clapperboard],['Dirty Birdy! Development','Software contribution, game mechanics, system thinking, UI/UX implementation, character universe and trailer storyboard work.',Gamepad2]] as [string,string,React.ComponentType<Record<string, unknown>>][]).map(([t,p,Icon])=><TiltCard className={`${s.cvCard} group relative`} key={t as string}><Icon/><h3>{t as string}</h3><p>{p as string}</p></TiltCard>)}</div></Section>
    <Section id="skills" label="09 / Skill inventory" title="Technical + Creative Inventory"><div className={s.inventoryGrid}>{([['Technical',['Python','C','C++','C#','Kotlin','Unity','GitHub','React','Node.js','TypeScript','MCP'],Code2],['Creative',['Character Design','Storyboarding','Cinematic Scriptwriting','Visual Storytelling','Ready PSD Animation','AI Image-to-Motion','Motion Graphics','After Effects Automation'],Sparkles],['Languages',['Turkish Native','English C1','German B1','Spanish A1'],GraduationCap],['Activities',['eTwinning European Quality Label','Piano performance','Debate club','Leadership'],Trophy]] as [string,string[],React.ComponentType<Record<string, unknown>>][]).map(([t,list,Icon])=><div className={s.inventory} key={t as string}><Icon/><h3>{t as string}</h3>{(list as string[]).map(x=><span key={x}>{x}</span>)}</div>)}</div></Section>
  </main>
}
